---
- name: Install system dependencies
  apt:
    name:
      - git
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com | sh
  args:
    executable: /bin/bash

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add ubuntu user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
